---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

provisioner:
  name: chef_zero
  always_update_cookbooks: true

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[java-app]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes: {}